kind: ServiceAccount
apiVersion: v1
metadata:
  name: resource-operator-controller-manager
  namespace: pacman-app
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resource-operator-controller-manager
subjects:
  - kind: ServiceAccount
    name: resource-operator-controller-manager
    namespace: pacman-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin