apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: toweraccess
  namespace: pacman-app
spec:
  encryptedData:
    host: AgBC1Rlbn2HtgOgsC6oCW45HmDwbLRE4nEs4T2G42qO53ixvb/Cbzn4UwSQEwpwCSHjoK6EvtCeU6ng99HhvB4gX7L2wSjLldCZ6PcsNiXcPYJZr4HlujRx+PHmbYUrdJj/1CZcfbF+2IQdZ+iHNkz4og7D7B+DBiyjedo+bLqqKOGx28rLC+U6G9sglM4vOLH4i9kJlUZoc1+9Yus0NgqJ2SEzaVTUblF7cm3oWFSCFft7qnCt8bHKdMUWB42IUpDGQ2jkhOQFUV1lFcDW74zXZ3UtTI8ibIRHER6RKqGWpe3U7a8efyqpa/xfIWfO3hoCtUQQziU+YkHeLfAno6OcIT1BhkstsZeg5WSCMHrxrGOktFCKW4orwxvdcDBWjiIySSqxBtDvLXqjkWghhhOv+JCh9Vt2qCQ41z3rHAx1UWYzsVU0APZovFsoqZihD+dxOh1k6F4R9V94/WiYYZpy8/UFvBEqh3ajFdN8WSAd0gZyxSVI+Wzb9pJ0dGSeJg7NsvNcmnwbiYlvJIUVKA8ka4Ly11Lrn2M05DG7uGoCZBAB/LSTNWGYFcqYo+DcIsIajxHv+QuMLFtLK6bARl7X2Vhw3qHIVFbnArsSTtyEmCOE+GFP/lfbYXWLy6arHreA0h578zq/0Yx/qY2Q2hpuYz4zAqLyHuByVm+gei5xdgqfqMat5wFs8ej9xcYA6aqRl3BWESFyuH9YYBDIFDB4PNwqv+ISYHNTYeqdTg0FbpcdiABBdFXtELl0KbT0RHgn65DW2cJCFLqfKmu25SPXWWITZu7ruOvVUT1j+eZw6
    token: AgAoWVk1gOiDr8j0X/N9q1LBEENgqvjcNbXfekdtfWGS4JN5OCUHSHf4sDC4Q/9CmXmAVkhu2Ha2vAjwAUBwDJFBLMqZzFyphsenNmSGsUQOaR5XSs2xU7CQy7Ilj7QvKuuCpDUinWqrRCN5VrcpRvXQH7uWud6iF5D0c5gIqZPI3w/Ma50nSJUQAve+nnAICck1XNp3oqnF92zueAK3+o88tXlCUDf3TjwxtizJWyTY6kdh5wneT64zFy9I4P9upcVfRE0VyEbvn41iNqCjWJ6CLhVtN6LH9eykJwG0+Cov3zv5YVKK/kYQZ5AZzkgwyrgmyZ+vIsnj41Y8tzMbhiDdEIUlruko/wuIXuAOQMOq6Uothwk8i2uPClXM63dp2lY1a/ZeH6R13jTh8FX6a4GPdcsnM+4rsZ4copSl/Kgk4iYGrgja+22Y0VzhONFoiKw76BMWxn4UWC8oYazZnkShHwoNF5Ph/pXtInNHzmFKY7RSV/R7ueRVXW8nI9XuGxE4g9IMN1tLcCLgCgsgXePCzb154PwSnP3yUfq3PdQLIKXZIXa1U3CuZ0sEIzU/8/JCaKvYxub9jJ2v0OrouMMYgyMXQLOnqtPvJv94oZyKRDOWOGGgDP+26lzmwmrwQjq/jJgiPbAFdtAvUZk2mk/4tFtnZRi7OX1jQEoP4JHOOpCprB/sQ1LDVgg8mt0ofhwy2tlT3fiaQshvIH0qgq1CeB6bVdz2QiC1ghnXzmg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: toweraccess
      namespace: pacman-app
    type: Opaque

