apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: /policies
    apps.open-cluster-management.io/reconcile-rate: high
  name: policies-subscription
  namespace: policies
spec:
  channel: acm-playground-channel
  placement:
    local: true #only deploy on the ACM hub cluster
  