---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: 01-send-slack-end
  namespace: pacman-app
  labels:
    app.kubernetes.io/name: pacman
spec:
  tower_auth_secret: toweraccess
  extra_vars:
    message: "Pacman deployment ended on "
  job_template_name: send-slack-message
  tower_auth_secret: toweraccess