- name: "Add credential type: Service Now"
  awx.awx.tower_credential_type:
    name: "ServiceNow"
    kind: cloud
    state: present
    inputs:
      fields:
      - id: SNOW_USERNAME
        type: string
        label: Service Now Username
      - id: SNOW_INSTANCE
        type: string
        label: Service Now Instance Name (devXXXXX)
      - id: SNOW_PASSWORD
        type: string
        label: Service Now Password
        secret: true
      required:
        - SNOW_USERNAME
        - SNOW_INSTANCE
        - SNOW_PASSWORD
    injectors:
      extra_vars:
        snow_username: '{%raw%}{{ SNOW_USERNAME }}{%endraw%}'
        snow_password: '{%raw%}{{ SNOW_PASSWORD }}{%endraw%}'
        snow_instance: '{%raw%}{{ SNOW_INSTANCE }}{%endraw%}'

- name:  "Add credential: ServiceNow"
  awx.awx.tower_credential:
    name: ServiceNow Credential
    organization: Default
    credential_type: "ServiceNow"
    state: present
    inputs:
      SNOW_USERNAME: "{{ snow_username }}"
      SNOW_PASSWORD: "{{ snow_password }}"
      SNOW_INSTANCE: "{{ snow_instance }}"

- name: "Add Tower Project: \"snow-create-change-record\""
  awx.awx.tower_project:
    name: "snow-create-change-record"
    description: "Service Now Change Requests"
    organization: "Default"
    state: present
    scm_type: git
    scm_url: https://github.com/mdelder/ansible-servicenow.git

- name: "Add Job Template: \"snow-create-change-record\""
  awx.awx.tower_job_template:
    name: "snow-create-change-record"
    inventory: "Demo Inventory"
    project: "snow-create-change-record"
    playbook: "servicenow_changerequest.yml"
    ask_variables_on_launch: true
    credentials:
    - "ServiceNow Credential"

- name: "Add Tower Project: \"send-slack-message\""
  awx.awx.tower_project:
    name: "send-slack-message"
    description: "Send a Slack message"
    organization: "Default"
    state: present
    scm_type: git
    scm_url: https://github.com/adetalhouet/ansible-slack.git
    scm_branch: main

- name: "Add Job Template: \"send-slack-message\""
  awx.awx.tower_job_template:
    name: "send-slack-message"
    inventory: "Demo Inventory"
    project: "send-slack-message"
    playbook: "slack_send_message.yml"
    ask_variables_on_launch: true