apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: app-dev-role-binding
  annotations:
    policy.open-cluster-management.io/standards: Access Control
    policy.open-cluster-management.io/categories: Application Developer
    policy.open-cluster-management.io/controls: AC-3 Access Enforcement
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-rolebinding-example
        spec:
          remediationAction: inform
          severity: high
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["app-*"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: app-dev-rolebinding
                subjects:
                - kind: User
                  name: adetalhouet
                  apiGroup: rbac.authorization.k8s.io
                roleRef:
                  kind: Role 
                  name: app-dev-role
                  apiGroup: rbac.authorization.k8s.io
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-rolebinding
placementRef:
  name: placement-policy-rolebinding
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: app-dev-role-binding
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-rolebinding
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: cloud, operator: In, values: ["Amazon"]}
