apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: cluster-view-admin-role
  namespace: policies
  annotations:
    policy.open-cluster-management.io/standards: Access Control
    policy.open-cluster-management.io/categories: Application Developer
    policy.open-cluster-management.io/controls: AC-3 Access Enforcement
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-cluster-view-admin-role
      spec:
        remediationAction: inform
        severity: high
        object-templates:
          - complianceType: mustonlyhave
            objectDefinition:
              apiVersion: rbac.authorization.k8s.io/v1
              kind: ClusterRole
              metadata:
                name: cluster-view-admin-role
              rules:
                - verbs:
                    - get
                    - list
                    - watch
                    - describe
                  apiGroups:
                    - '*'
                  resources:
                    - '*'
                - verbs:
                    - get
                    - list
                    - watch
                    - describe
                  nonResourceURLs:
                    - '*'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: cluster-view-admin-role
  namespace: policies
placementRef:
  name: placement-cluster-view-admin-role
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: cluster-view-admin-role
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-cluster-view-admin-role
  namespace: policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: cloud, operator: In, values: ["Amazon"]}
