apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: cluster-view-admin-role-binding
  annotations:
    policy.open-cluster-management.io/standards: Access Control
    policy.open-cluster-management.io/categories: Application Developer
    policy.open-cluster-management.io/controls: AC-3 Access Enforcement
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-cluster-view-admin-role-binding
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              pruneObjectBehavior: DeleteIfCreated
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: cluster-view-admin-role-binding
                subjects:
                - kind: Group
                  name: cluster-view-admin
                  apiGroup: rbac.authorization.k8s.io
                roleRef:
                  kind: ClusterRole
                  name: cluster-view-admin-role
                  apiGroup: rbac.authorization.k8s.io
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-cluster-view-admin-role-binding
placementRef:
  name: placement-cluster-view-admin-role
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: cluster-view-admin-role-binding
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-cluster-view-admin-role
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: governanceEnabled, operator: In, values: ["True"]}
