apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: sandbox1829.opentlc.com-certificate
  namespace: policies
  annotations:
    policy.open-cluster-management.io/standards: Infrastructure security
    policy.open-cluster-management.io/categories: Data security
    policy.open-cluster-management.io/controls: PR.DS-2 Data-in-transit
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: CertificatePolicy
        metadata:
          name: policy-certificatepolicy-cert-expiration
        spec:
          allowedSANPattern: '.adetalhouet.ca|.openshift-ingress.'
          minimumDuration: 300h
          namespaceSelector:
            include:
              - openshift-ingress
          remediationAction: inform
          severity: low
  remediationAction: inform
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-certificate
  namespace: policies
placementRef:
  name: placement-policy-certificate
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: sandbox1829.opentlc.com-certificate
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-certificate
  namespace: policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: governanceEnabled, operator: In, values: ["True"]}