apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: cis-scan
  namespace: policies
  annotations:
    policy.open-cluster-management.io/standards: Infrastructure security
    policy.open-cluster-management.io/categories: Configuration Management
    policy.open-cluster-management.io/controls: CM-6 Configuration Settings
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: compliance-scan-settings
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: compliance.openshift.io/v1alpha1
                kind: ScanSetting
                metadata:
                  name: default-submariner
                  namespace: openshift-compliance
                rawResultStorage:
                  pvAccessModes:
                  - ReadWriteOnce
                  rotation: 3
                  size: 1Gi
                  storageClassName: ocs-storagecluster-ceph-rbd
                roles:
                - worker
                - master
                scanTolerations:
                - effect: NoSchedule
                  key: node-role.kubernetes.io/master
                  operator: Exists
                - effect: NoSchedule
                  key: node-role.submariner.io/gateway
                  operator: Exists
                schedule: 0 1 * * *
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: compliance-cis-scan
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: compliance.openshift.io/v1alpha1
                kind: ScanSettingBinding
                metadata:
                  name: cis
                  namespace: openshift-compliance
                profiles:
                  - name: ocp4-cis
                    apiGroup: compliance.openshift.io/v1alpha1
                    kind: Profile
                  - name: ocp4-cis-node
                    apiGroup: compliance.openshift.io/v1alpha1
                    kind: Profile
                settingsRef:
                  name: default-submariner
                  apiGroup: compliance.openshift.io/v1alpha1
                  kind: ScanSetting
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: compliance-suite-cis
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: compliance.openshift.io/v1alpha1
                kind: ComplianceSuite
                metadata:
                  name: cis
                  namespace: openshift-compliance
                status:
                  phase: DONE
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: compliance-suite-cis-results
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: compliance.openshift.io/v1alpha1
                kind: ComplianceCheckResult
                metadata:
                  namespace: openshift-compliance
                  labels:
                    compliance.openshift.io/check-status: FAIL
                    compliance.openshift.io/suite: cis
          remediationAction: enforce
          severity: high
  remediationAction: enforce
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-cis-scan
  namespace: policies
placementRef:
  name: placement-policy-cis-scan
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: cis-scan
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-cis-scan
  namespace: policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: governanceEnabled, operator: In, values: ["True"]}