apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: etcd-encryption
  namespace: policies
  annotations:
    policy.open-cluster-management.io/standards: Infrastructure security
    policy.open-cluster-management.io/categories: Data security
    policy.open-cluster-management.io/controls: PR.DS-1 Data-at-rest
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-etcdencryption-etcd-encryption
      spec:
        remediationAction: inform
        severity: medium
        object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: config.openshift.io/v1
              kind: APIServer
              metadata:
                name: cluster
              spec:
                encryption:
                  type: aescbc
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-etcdencryption
  namespace: policies
placementRef:
  name: placement-policy-etcdencryption
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: etcd-encryption
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-etcdencryption
  namespace: policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: governanceEnabled, operator: In, values: ["True"]}
