apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: limit-cluster-admin
  namespace: policies
  annotations:
    policy.open-cluster-management.io/standards: Infrastructure security
    policy.open-cluster-management.io/categories: Access Control
    policy.open-cluster-management.io/controls: AC-3 Access Enforcement
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: IamPolicy
      metadata:
        name: policy-limitclusteradmin-example
      spec:
        severity: medium
        namespaceSelector:
          include:
            - '*'
          exclude:
            - kube-*
            - openshift-*
        remediationAction: inform
        maxClusterRoleBindingUsers: 5
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-limitclusteradmin
  namespace: policies
placementRef:
  name: placement-policy-limitclusteradmin
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: limit-cluster-admin
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-limitclusteradmin
  namespace: policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: cloud, operator: In, values: ["Amazon"]}
