apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: limit-memory-range
  namespace: policies
  annotations:
    policy.open-cluster-management.io/standards: Application security
    policy.open-cluster-management.io/categories: Configuration Management
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-limit-range-container-mem-limit-range
      spec:
        remediationAction: inform # will be overridden by remediationAction in parent policy
        severity: medium
        namespaceSelector:
          exclude: ["kube-*"]
          include: ["default"]
        object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: v1
              kind: LimitRange # limit memory usage
              metadata:
                name: container-mem-limit-range
              spec:
                limits:
                - default:
                    memory: 512Mi
                  defaultRequest:
                    memory: 256Mi
                  type: Container
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-limit-range
  namespace: policies
placementRef:
  name: placement-policy-limit-range
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: limit-memory-range
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-limit-range
  namespace: policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: cloud, operator: In, values: ["Amazon"]}
