---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: 02-send-slack-start
  namespace: pacman-app
  labels:
    app.kubernetes.io/name: pacman
spec:
  extra_vars:
    message: "Pacman deployment started on "
  job_template_name: send-slack-message
  tower_auth_secret: toweraccess